const express = require('express')
const app = express()
const port = 3000
const pool = require('./connectDB')
const cors = require('cors')

app.use(cors())
app.use(express.json())
const Student = require('./routes/Student')
const Teacher = require('./routes/Teacher')
const Score = require('./routes/Score')
const Major = require('./routes/Major')
const Schedule = require('./routes/Schedule')
const Subject = require('./routes/Subject')
const Class_Student = require('./routes/ClassStudent')
const Class = require('./routes/Class')
const Attendance = require('./routes/Attendance')
const login = require('./routes/login')
app.use('/Student', Student)
app.use('/Teacher', Teacher)
app.use('/Score', Score)
app.use('/Major', Major)
app.use('/Schedule', Schedule)
app.use('/Subject', Subject)
app.use('/ClassStudent', Class_Student)
app.use('/Class', Class)
app.use('/Attendance', Attendance)
app.use('/auth', login)
app.get('/success', (req, res) => {
  res.send("GET Request Called")
})
app.listen(port, () => {
  console.log(`app listening at http://localhost:${port}`)
})
